### ISSUE TITLE
VHS-Tape: Tape DOM helper 

### ISSUE THREAD

**Issue by bcomnes** [hyperdivision/nanotron#2]
A tape helper or tape replacement that includes helper methods for interacting with DOM components.

**Comment by emilbayes** [comment]
https://www.npmjs.com/package/vhs-tape

**Comment by bcomnes** [comment]
Related https://github.com/hyperdivision/nanotron/issues/3

**Comment by bcomnes** [comment]
This is pretty much done! 

https://github.com/hyperdivision/vhs-tape

Works great with nanotron.
